name: CI

on:
  push:
    branches:
      - master
      - 'dev/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
      
jobs:
  integration-test-live:
    uses: ./.github/workflows/ci-integration-db-live.yaml
  integration-test-non-live:
    uses: ./.github/workflows/ci-integration-db.yaml
  test:
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pkgmt codespell
          pkgmt lint


      - name: Install dependencies
        run: |

          pip install .
          # check package is importable
          python -c "import sql"
          pip install ".[dev]"
          pip install sqlalchemy -U

      - name: Test with pytest
        run: |
          # ensure we're running sqlalchemy 2
          python -c "import sqlalchemy; assert int(sqlalchemy.__version__.split('.')[0]) == 2"
          # run unit tests
          pytest --durations-min=5 --ignore=src/tests/integration

  test-sqlalchemy-v1:
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint
        run: |
          python -m pip install --upgrade pip pkgmt
          pkgmt lint

      - name: Install dependencies
        run: |
          pip install "sqlalchemy<2"
          pip install ".[dev]"

      - name: Test with pytest
        run: |
          # ensure we're running sqlalchemy 1
          python -c "import sqlalchemy; assert int(sqlalchemy.__version__.split('.')[0]) == 1"
          # run tests
          pytest --durations-min=5 --ignore=src/tests/integration

  # run: pkgmt check
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pkgmt[check]'

      - name: Check project
        run: |
          pkgmt check


  release:
    needs: [test, test-sqlalchemy-v1, check, integration-test-non-live, integration-test-live]
    if: startsWith(github.ref, 'refs/tags') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install pkgmt twine wheel --upgrade

      - name: Release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TAG: ${{  github.ref_name }}
        run: |
          echo "tag is $TAG"
          pkgmt release $TAG --production --yes